name: CI Pipeline Execution

on:
  # Se ejecuta ante cualquier push en main o ramas feature, y en Pull Requests
  push:
    branches: [ main, feature-* ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest # Usamos un runner de Linux (máquina virtual) para ejecutar el workflow

    steps:
    - name: 1. Checkout Code
      uses: actions/checkout@v4
      # Descarga el código del repositorio en el runner

    - name: 2. Setup Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
      # Configura el entorno Python 3.10

    - name: 3. Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # Asumo que las dependencias clave (pandas, scikit-learn) están en requirements.txt
        pip install -r requirements.txt
        pip install pytest # Instalamos pytest para ejecutar los tests
        
    - name: 4. Run Unit Tests (pytest)
      # Ejecuta el framework de pruebas. La acción fallará si algún test falla.
      run: |
        pytest tests/test_preprocesamiento.py

    - name: 5. Verify Documentation File Exists
      run: |
        # Verificación simple para asegurar que el archivo de documentación esté presente
        if [ ! -f "DOCUMENTACION.md" ]; then
          echo "Error: DOCUMENTACION.md is missing!"
          exit 1
        fi
        echo "DOCUMENTACION.md found successfully."